# Generated by Django 6.0.1 on 2026-02-17 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('NEEDS_FIX', 'Needs Fix'), ('INVALIDATED', 'Invalidated'), ('CADET_APPROVED', 'Cadet Approved'), ('OFFICER_DEFECT', 'Officer Defect'), ('OFFICER_APPROVED', 'Officer Approved')], default='SUBMITTED', max_length=32)),
                ('bad_submission_count', models.PositiveSmallIntegerField(default=0)),
                ('cadet_error_message', models.TextField(blank=True, default='')),
                ('officer_error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadet_assigned_intake_complaints', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_complaints', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_assigned_intake_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
