# Generated by ChatGPT

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_crime_level_captaindecision_casenotification_and_more"),
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="case",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="intake_complaint", to="cases.case"),
        ),
    ]
