# Generated by Django 6.0.1 on 2026-02-18 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_rename_casecomp_case_status_idx_cases_casec_case_id_baf018_idx_and_more'),
        ('intake', '0002_complaint_case_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intake_complaints', to='cases.case'),
        ),
    ]
