# Generated by Django 6.0.1 on 2026-02-03 16:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_name', models.CharField(max_length=200)),
                ('info', models.TextField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('OFFICER_REJECTED', 'Officer Rejected'), ('OFFICER_APPROVED', 'Officer Approved'), ('DETECTIVE_APPROVED', 'Detective Approved')], default='SUBMITTED', max_length=30)),
                ('unique_code', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
