# Generated by Django 6.0.1 on 2026-02-18 03:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardtip',
            old_name='info',
            new_name='message',
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='approved_by_detective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_tips_as_detective', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='citizen_name',
            field=models.CharField(default='Unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='citizen_national_id',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='citizen_phone',
            field=models.CharField(default='0000000000', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='detective_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='detective_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='officer_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='officer_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='reviewed_by_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_tips_as_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardtip',
            name='suspect_last_seen',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
