# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suspects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="suspect",
            name="national_id",
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name="suspect",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="suspect",
            name="photo_url",
            field=models.URLField(blank=True),
        ),
    ]
