# Generated by Django 5.2.11 on 2026-02-21 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(blank=True, null=True)),
                ('suspect_id', models.IntegerField(blank=True, null=True)),
                ('crime_level', models.PositiveSmallIntegerField()),
                ('purpose', models.CharField(choices=[('BAIL', 'Bail'), ('FINE', 'Fine')], max_length=10)),
                ('amount_rials', models.PositiveBigIntegerField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('INITIATED', 'Initiated'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('gateway', models.CharField(default='mock', max_length=30)),
                ('authority', models.CharField(blank=True, default='', max_length=128)),
                ('ref_id', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_requests', to=settings.AUTH_USER_MODEL)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
