import { useState } from "react";

import MainLayout from "../components/layout/MainLayout";
import Card from "../components/Card";
import Input from "../components/Input";
import Button from "../components/Button";

import type { CaseReport } from "../types/report";
import { generateCaseReport } from "../services/reportsService";
import { getApiErrorMessage } from "../services/apiErrors";

export default function ReportsPage() {
  const [caseId, setCaseId] = useState("C-1001");
  const [loading, setLoading] = useState(false);
  const [report, setReport] = useState<CaseReport | null>(null);
  const [error, setError] = useState<string | null>(null);

  const onGenerate = async () => {
    const id = caseId.trim();
    if (!id) return;

    setLoading(true);
    setError(null);

    try {
      const data = await generateCaseReport(id);
      setReport(data);
    } catch (e) {
      setReport(null);
      setError(getApiErrorMessage(e));
    } finally {
      setLoading(false);
    }
  };

  return (
    <MainLayout title="Reports">
      <div style={{ display: "grid", gap: 14 }}>
        <Card title="Generate report">
          <div
            className="no-print"
            style={{ display: "grid", gap: 12, gridTemplateColumns: "1fr auto auto" }}
          >
            <Input
              label="Case ID"
              value={caseId}
              onChange={(e) => setCaseId(e.target.value)}
              placeholder="e.g. C-1"
            />

            <div style={{ alignSelf: "end" }}>
              <Button onClick={() => void onGenerate()} disabled={loading || !caseId.trim()}>
                {loading ? "Generating..." : "Generate"}
              </Button>
            </div>

            <div style={{ alignSelf: "end" }}>
              <Button variant="secondary" onClick={() => window.print()} disabled={!report}>
                Print / Save as PDF
              </Button>
            </div>
          </div>

          {error ? (
            <p style={{ marginTop: 10, color: "crimson", fontWeight: 800 }}>{error}</p>
          ) : null}
        </Card>

        <div className="print-area">
          <Card title="Report preview">
            {!report ? (
              <p style={{ margin: 0, color: "var(--muted)" }}>
                Generate a report to see the preview here.
              </p>
            ) : (
              <ReportPreview report={report} />
            )}
          </Card>
        </div>
      </div>
    </MainLayout>
  );
}

function ReportPreview({ report }: { report: CaseReport }) {
  return (
    <div style={{ display: "grid", gap: 12 }}>
      <div style={{ display: "grid", gap: 4 }}>
        <div style={{ fontSize: 18, fontWeight: 900 }}>Case report</div>
        <div style={{ fontSize: 13, color: "var(--muted)" }}>
          Report ID: <strong>{report.id}</strong> • Generated at{" "}
          <strong>{new Date(report.generatedAt).toLocaleString()}</strong>
        </div>
        <div style={{ fontSize: 13, color: "var(--muted)" }}>
          Generated by: <strong>{report.generatedBy.fullName}</strong> ({report.generatedBy.role})
        </div>
      </div>

      <Section title="Case summary">
        <Row label="Case ID" value={report.case.id} />
        <Row label="Title" value={report.case.title} />
        <Row label="Status" value={report.case.status} />
        <Row label="Type" value={report.case.complaintType} />
        <Row label="Created" value={new Date(report.case.createdAt).toLocaleString()} />
        <Row
          label="Last update"
          value={report.case.updatedAt ? new Date(report.case.updatedAt).toLocaleString() : "—"}
        />
      </Section>

      <Section title="Description">
        <p style={{ margin: 0, color: "var(--muted)" }}>{report.case.description}</p>
      </Section>

      <Section title="Reporter">
        <Row label="Name" value={report.case.reporterName ?? "—"} />
        <Row label="Contact" value={report.case.reporterContact ?? "—"} />
      </Section>

      <Section title="Attachments">
        <Row label="Evidence IDs" value={report.case.evidenceIds.join(", ") || "—"} />
        <Row label="Suspect IDs" value={report.case.suspectIds.join(", ") || "—"} />
      </Section>

      {report.notes ? (
        <Section title="Notes">
          <p style={{ margin: 0, color: "var(--muted)" }}>{report.notes}</p>
        </Section>
      ) : null}
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div
      style={{
        border: "1px solid var(--border)",
        borderRadius: 14,
        padding: 12,
        background: "white",
      }}
    >
      <div style={{ fontWeight: 900, marginBottom: 8 }}>{title}</div>
      {children}
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div style={{ display: "flex", gap: 8, padding: "4px 0" }}>
      <div style={{ width: 120, color: "var(--muted)" }}>{label}</div>
      <div style={{ fontWeight: 700 }}>{value}</div>
    </div>
  );
}
