# Generated by Django 6.0.1 on 2026-02-03 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('GENERIC', 'Generic'), ('MEDICAL', 'Medical/Biological'), ('VEHICLE', 'Vehicle'), ('ID_DOC', 'ID Document')], default='GENERIC', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_url', models.URLField(blank=True, default='')),
                ('medical_result', models.TextField(blank=True, default='')),
                ('vehicle_model', models.CharField(blank=True, default='', max_length=100)),
                ('vehicle_color', models.CharField(blank=True, default='', max_length=50)),
                ('plate_number', models.CharField(blank=True, default='', max_length=30)),
                ('serial_number', models.CharField(blank=True, default='', max_length=50)),
                ('id_fields', models.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='cases.case')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
