# Generated by ChatGPT

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0004_readd_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidence",
            name="transcription",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="evidence",
            name="media_urls",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="evidence",
            name="evidence_type",
            field=models.CharField(
                choices=[
                    ("MEDICAL", "Medical"),
                    ("VEHICLE", "Vehicle"),
                    ("ID_DOC", "ID Document"),
                    ("OTHER", "Other"),
                    ("WITNESS", "Witness"),
                ],
                max_length=20,
            ),
        ),
    ]
