# Generated by Django 6.0.1 on 2026-02-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0005_witness_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='evidence_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('MEDICAL', 'Medical/Biological'), ('VEHICLE', 'Vehicle'), ('ID_DOC', 'ID Document'), ('WITNESS', 'Witness')], default='GENERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='transcription',
            field=models.TextField(blank=True, default=''),
        ),
    ]
