# Generated by Django 5.2.11 on 2026-02-22 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_alter_evidence_evidence_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
