# Generated by Django 6.0.1 on 2026-02-03 15:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Under Review'), ('OPEN', 'Open'), ('CLOSED', 'Closed'), ('INVALIDATED', 'Invalidated')], default='DRAFT', max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('revision_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to='cases.case')),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CrimeSceneReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('witnessed_phone', models.CharField(blank=True, default='', max_length=20)),
                ('witnessed_national_id', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crime_scene', to='cases.case')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scene_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
