# Generated by Django 6.0.1 on 2026-02-16 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crimescenereport',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crimescenereport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_crime_scenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crimescenereport',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
