# Generated by Django 6.0.1 on 2026-02-18 00:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_detectiveboard_detectiveboarditem_detectiveboardlink'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='crime_level',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Critical')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.CreateModel(
            name='CaptainDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('SEND_TO_TRIAL', 'Send to trial'), ('RELEASE', 'Release')], max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chief_approved', models.BooleanField(blank=True, null=True)),
                ('chief_at', models.DateTimeField(blank=True, null=True)),
                ('chief_comment', models.TextField(blank=True, default='')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='captain_decision', to='cases.case')),
                ('chief_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chief_approvals', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captain_decisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaseNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('EVIDENCE_ADDED', 'Evidence added'), ('INFO', 'Info')], default='INFO', max_length=30)),
                ('message', models.TextField()),
                ('ref_model', models.CharField(blank=True, default='', max_length=50)),
                ('ref_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cases.case')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('GUILTY', 'Guilty'), ('INNOCENT', 'Innocent')], max_length=20)),
                ('punishment_title', models.CharField(blank=True, default='', max_length=200)),
                ('punishment_description', models.TextField(blank=True, default='')),
                ('judged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case')),
                ('judged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trials_judged', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interrogation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_id', models.PositiveIntegerField()),
                ('detective_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('sergent_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interrogations', to='cases.case')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('case', 'suspect_id'), name='uniq_interrogation_case_suspect')],
            },
        ),
        migrations.CreateModel(
            name='SolveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suspect_ids', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='SUBMITTED', max_length=20)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solve_requests', to='cases.case')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solve_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solve_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'SUBMITTED')), fields=('case',), name='uniq_pending_solve_request_per_case')],
            },
        ),
    ]
