# Generated by ChatGPT

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0004_case_crime_level_captaindecision_casenotification_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseComplainant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")], default="PENDING", max_length=20)),
                ("cadet_message", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("case", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="complainant_links", to="cases.case")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_case_complainants", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="case_complainant_links", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("case", "user")},
            },
        ),
        migrations.AddIndex(
            model_name="casecomplainant",
            index=models.Index(fields=["case", "status"], name="casecomp_case_status_idx"),
        ),
        migrations.AddIndex(
            model_name="casecomplainant",
            index=models.Index(fields=["user", "status"], name="casecomp_user_status_idx"),
        ),
    ]
