# Generated by Django 6.0.1 on 2026-02-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_casecomplainant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casecomplainant',
            new_name='cases_casec_case_id_baf018_idx',
            old_name='casecomp_case_status_idx',
        ),
        migrations.RenameIndex(
            model_name='casecomplainant',
            new_name='cases_casec_user_id_6e8e6d_idx',
            old_name='casecomp_user_status_idx',
        ),
    ]
